# Generated by Django 5.1.4 on 2024-12-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='user',
            field=models.IntegerField(max_length=10),
        ),
    ]
