# Generated by Django 5.1.4 on 2024-12-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_room_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room',
        ),
    ]
